In [2]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/gdp-per-capita-worldbank.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/gdp-per-capita-worldbank.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [3]:
df.head()

        Entity Code  Year  ny_gdp_pcap_pp_kd
0  Afghanistan  AFG  2000          1617.8264
1  Afghanistan  AFG  2001          1454.1108
2  Afghanistan  AFG  2002          1774.3087
3  Afghanistan  AFG  2003          1815.9282
4  Afghanistan  AFG  2004          1776.9182

In [4]:
df_2 = df[df["Year"] == 2023].reset_index(drop=True)
df_2 = df_2[["Code", "ny_gdp_pcap_pp_kd"]]
df_2 = df_2.rename(columns={"Code": "LOCATION"})

df_2.head(20)

   LOCATION  ny_gdp_pcap_pp_kd
0       AFG          1992.4244
1       ALB         18244.2930
2       DZA         15159.3240
3       AND         64631.2970
4       AGO          7244.8930
5       ATG         28967.2560
6       ARG         27104.9800
7       ARM         19230.1900
8       ABW         40516.8100
9       AUS         59552.8800
10      AUT         65015.1330
11      AZE         21262.2990
12      BHS         33105.6050
13      BHR         57213.0900
14      BGD          8242.3980
15      BRB         19224.4630
16      BLR         27718.3220
17      BEL         64185.8480
18      BLZ         12455.2960
19      BEN          3721.2246

In [5]:
df_tabla = pd.read_csv("OECD,DF_BLI,+all.csv")
df_tabla.head(5)

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,LOCATION,Unnamed: 5,INDICATOR,Unnamed: 7,MEASURE,Unnamed: 9,...,OBS_VALUE,Unnamed: 13,OBS_STATUS,Unnamed: 15,UNIT_MEASURE,Unnamed: 17,UNIT_MULT,Unnamed: 19,BASE_PER,Unnamed: 21
0,DATAFLOW,OECD:DF_BLI(1.0),NaN,I,AUT,NaN,JE_LMIS,NaN,L,NaN,...,2.3,NaN,A,NaN,PC,NaN,0,NaN,NaN,NaN
1,DATAFLOW,OECD:DF_BLI(1.0),NaN,I,BEL,NaN,JE_LMIS,NaN,L,NaN,...,2.4,NaN,A,NaN,PC,NaN,0,NaN,NaN,NaN
2,DATAFLOW,OECD:DF_BLI(1.0),NaN,I,CAN,NaN,JE_LMIS,NaN,L,NaN,...,3.8,NaN,A,NaN,PC,NaN,0,NaN,NaN,NaN
3,DATAFLOW,OECD:DF_BLI(1.0),NaN,I,CZE,NaN,JE_LMIS,NaN,L,NaN,...,2.3,NaN,A,NaN,PC,NaN,0,NaN,NaN,NaN
4,DATAFLOW,OECD:DF_BLI(1.0),NaN,I,DNK,NaN,JE_LMIS,NaN,L,NaN,...,4.5,NaN,A,NaN,PC,NaN,0,NaN,NaN,NaN

In [6]:
df_tabla2 = df_tabla[["LOCATION","INDICATOR","OBS_VALUE"]]
df_tabla2.head(5)

  LOCATION INDICATOR  OBS_VALUE
0      AUT   JE_LMIS        2.3
1      BEL   JE_LMIS        2.4
2      CAN   JE_LMIS        3.8
3      CZE   JE_LMIS        2.3
4      DNK   JE_LMIS        4.5

In [7]:

df_tabla3 = df_tabla2.groupby(["LOCATION", "INDICATOR"]).first().reset_index()

df_pivot = df_tabla3.pivot(index="LOCATION", columns="INDICATOR", values="OBS_VALUE")
df_pivot.head()

INDICATOR,CG_SENG,CG_VOTO,EQ_AIRP,EQ_WATER,ES_EDUA,ES_EDUEX,ES_STCS,HO_BASE,HO_HISH,HO_NUMR,...,JE_EMPL,JE_LMIS,JE_LTUR,JE_PEARN,PS_FSAFEN,PS_REPH,SC_SNTWS,SW_LIFS,WL_EWLH,WL_TNOW
LOCATION,,,,,,,,,,,,,,,,,,,,,
AUS,2.7,92.0,6.7,92.0,84.0,20.0,499.0,NaN,19.4,NaN,...,73.0,3.1,1.0,55206.0,54.0,0.9,93.0,7.1,12.5,14.36
AUT,1.3,76.0,12.2,92.0,86.0,17.0,491.0,0.8,20.8,1.6,...,72.0,2.3,1.3,53132.0,86.0,0.5,92.0,7.2,5.3,14.51
BEL,2.0,88.0,12.8,79.0,80.0,19.0,500.0,0.7,20.0,2.1,...,65.0,2.4,2.3,54327.0,56.0,1.1,90.0,6.8,4.3,15.52
BRA,2.2,80.0,11.7,70.0,57.0,16.0,400.0,6.7,NaN,NaN,...,57.0,NaN,NaN,NaN,45.0,19.0,83.0,6.1,5.6,NaN
CAN,2.9,68.0,7.1,90.0,92.0,17.0,517.0,0.2,22.9,2.6,...,70.0,3.8,0.5,55342.0,78.0,1.2,93.0,7.0,3.3,14.57

In [8]:
df_final = df_pivot.merge(df_2[["LOCATION", "ny_gdp_pcap_pp_kd"]], on="LOCATION", how="inner")

df_final.head()

,LOCATION,CG_SENG,CG_VOTO,EQ_AIRP,EQ_WATER,ES_EDUA,ES_EDUEX,ES_STCS,HO_BASE,HO_HISH,...,JE_LMIS,JE_LTUR,JE_PEARN,PS_FSAFEN,PS_REPH,SC_SNTWS,SW_LIFS,WL_EWLH,WL_TNOW,ny_gdp_pcap_pp_kd
0,AUS,2.7,92.0,6.7,92.0,84.0,20.0,499.0,NaN,19.4,...,3.1,1.0,55206.0,54.0,0.9,93.0,7.1,12.5,14.36,59552.880
1,AUT,1.3,76.0,12.2,92.0,86.0,17.0,491.0,0.8,20.8,...,2.3,1.3,53132.0,86.0,0.5,92.0,7.2,5.3,14.51,65015.133
2,BEL,2.0,88.0,12.8,79.0,80.0,19.0,500.0,0.7,20.0,...,2.4,2.3,54327.0,56.0,1.1,90.0,6.8,4.3,15.52,64185.848
3,BRA,2.2,80.0,11.7,70.0,57.0,16.0,400.0,6.7,NaN,...,NaN,NaN,NaN,45.0,19.0,83.0,6.1,5.6,NaN,19018.238
4,CAN,2.9,68.0,7.1,90.0,92.0,17.0,517.0,0.2,22.9,...,3.8,0.5,55342.0,78.0,1.2,93.0,7.0,3.3,14.57,55918.930

In [9]:
df_final.to_csv("indicatos_final.csv", index=False)

In [10]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   LOCATION           41 non-null     object
 1   CG_SENG            39 non-null     float64
 2   CG_VOTO            41 non-null     float64
 3   EQ_AIRP            41 non-null     float64
 4   EQ_WATER           41 non-null     float64
 5   ES_EDUA            40 non-null     float64
 6   ES_EDUEX           39 non-null     float64
 7   ES_STCS            39 non-null     float64
 8   HO_BASE            38 non-null     float64
 9   HO_HISH            37 non-null     float64
 10  HO_NUMR            38 non-null     float64
 11  HS_LEB             41 non-null     float64
 12  HS_SFRH            39 non-null     float64
 13  IW_HADI            35 non-null     float64
 14  IW_HNFW            29 non-null     float64
 15  JE_EMPL            41 non-null     float64
 16  JE_LMIS            34 non-null     float64
 17  JE_LTUR            39 non-null     float64
 18  JE_PEARN           35 non-null     float64
 19  PS_FSAFEN          41 non-null     float64
 20  PS_REPH            41 non-null     float64
 21  SC_SNTWS           41 non-null     float64
 22  SW_LIFS            41 non-null     float64
 23  WL_EWLH            39 non-null     float64
 24  WL_TNOW            22 non-null     float64
 25  ny_gdp_pcap_pp_kd  41 non-null     float64
dtypes: float64(25), object(1)
memory usage: 8.5+ KB

In [11]:
df_normalizados = pd.read_csv("indicadores_normalizados"".csv")

In [12]:
df_normalizados.head()

,LOCATION,CG_SENG,CG_VOTO,EQ_AIRP,EQ_WATER,ES_EDUA,ES_EDUEX,ES_STCS,HO_BASE,HO_HISH,...,JE_LMIS,JE_LTUR,JE_PEARN,PS_FSAFEN,PS_REPH,SC_SNTWS,SW_LIFS,WL_EWLH,WL_TNOW,ny_gdp_pcap_pp_kd
0,AUS,0.75,1.000000,0.947826,0.833333,0.792453,1.000000,0.785714,NaN,0.629921,...,0.898551,0.944134,0.733155,0.264151,0.973684,0.761905,0.733333,0.460967,0.890295,0.384894
1,AUT,0.05,0.659574,0.708696,0.833333,0.830189,0.500000,0.722222,0.977716,0.519685,...,0.937198,0.927374,0.694142,0.867925,0.988722,0.714286,0.766667,0.193309,0.827004,0.430735
2,BEL,0.40,0.914894,0.682609,0.472222,0.716981,0.833333,0.793651,0.980501,0.582677,...,0.932367,0.871508,0.716621,0.301887,0.966165,0.619048,0.633333,0.156134,0.400844,0.423775
3,BRA,0.50,0.744681,0.730435,0.222222,0.283019,0.333333,0.000000,0.813370,NaN,...,NaN,NaN,NaN,0.094340,0.293233,0.285714,0.400000,0.204461,NaN,0.044713
4,CAN,0.85,0.489362,0.930435,0.777778,0.943396,0.500000,0.928571,0.994429,0.354331,...,0.864734,0.972067,0.735713,0.716981,0.962406,0.761905,0.700000,0.118959,0.801688,0.354397

In [13]:
df_normalizados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   LOCATION           41 non-null     object
 1   CG_SENG            39 non-null     float64
 2   CG_VOTO            41 non-null     float64
 3   EQ_AIRP            41 non-null     float64
 4   EQ_WATER           41 non-null     float64
 5   ES_EDUA            40 non-null     float64
 6   ES_EDUEX           39 non-null     float64
 7   ES_STCS            39 non-null     float64
 8   HO_BASE            38 non-null     float64
 9   HO_HISH            37 non-null     float64
 10  HO_NUMR            38 non-null     float64
 11  HS_LEB             41 non-null     float64
 12  HS_SFRH            39 non-null     float64
 13  IW_HADI            35 non-null     float64
 14  IW_HNFW            29 non-null     float64
 15  JE_EMPL            41 non-null     float64
 16  JE_LMIS            34 non-null     float64
 17  JE_LTUR            39 non-null     float64
 18  JE_PEARN           35 non-null     float64
 19  PS_FSAFEN          41 non-null     float64
 20  PS_REPH            41 non-null     float64
 21  SC_SNTWS           41 non-null     float64
 22  SW_LIFS            41 non-null     float64
 23  WL_EWLH            39 non-null     float64
 24  WL_TNOW            22 non-null     float64
 25  ny_gdp_pcap_pp_kd  41 non-null     float64
dtypes: float64(25), object(1)
memory usage: 8.5+ KB

In [14]:
df_normalizados["Mean"] = df_normalizados.iloc[:,1:].mean(axis=1)

In [15]:
df_normalizados = df_normalizados.sort_values(by="Mean", ascending=False)

In [16]:

df_normalizados.head()

,LOCATION,CG_SENG,CG_VOTO,EQ_AIRP,EQ_WATER,ES_EDUA,ES_EDUEX,ES_STCS,HO_BASE,HO_HISH,...,JE_LTUR,JE_PEARN,PS_FSAFEN,PS_REPH,SC_SNTWS,SW_LIFS,WL_EWLH,WL_TNOW,ny_gdp_pcap_pp_kd,Mean
20,ISL,0.45,0.765957,0.960870,0.972222,0.641509,0.833333,0.642857,1.000000,NaN,...,0.960894,0.964185,0.849057,0.996241,1.000000,0.900000,0.431227,NaN,0.449538,0.803168
39,USA,0.95,0.425532,0.904348,0.722222,0.943396,0.500000,0.753968,0.997214,0.716535,...,0.972067,1.000000,0.716981,0.781955,0.809524,0.700000,0.382900,0.801688,0.510986,0.776177
0,AUS,0.75,1.000000,0.947826,0.833333,0.792453,1.000000,0.785714,NaN,0.629921,...,0.944134,0.733155,0.264151,0.973684,0.761905,0.733333,0.460967,0.890295,0.384894,0.768047
37,SWE,0.40,0.893617,0.986957,0.972222,0.792453,1.000000,0.817460,1.000000,0.574803,...,0.944134,0.579173,0.735849,0.966165,0.809524,0.800000,0.029740,NaN,0.414786,0.745905
30,NOR,0.50,0.702128,0.947826,1.000000,0.754717,0.666667,0.769841,1.000000,0.763780,...,0.949721,0.743952,1.000000,0.984962,0.904762,0.800000,0.048327,0.337553,0.644359,0.744226

In [ ]:
import plotly.express as px

top_n = 25
df_top = df_normalizados.head(top_n)

fig = px.bar(
    df_top,
    x="Mean",
    y=df_top.columns[0],
    orientation='h',
    color="Mean",  
    color_continuous_scale="Viridis",
    text="Mean", 
    title=f"Top {top_n} Países por Promedio de Indicadores"
)
fig.update_traces(texttemplate='%{text:.2f}', textposition='outside')
fig.update_layout(
    width=800,
    height=600,
    yaxis={'categoryorder':'total ascending'},  
    xaxis_title="Promedio de Indicadores",
    yaxis_title="País"
)
fig.show()

In [46]:
import plotly.express as px
import numpy as np


corr = df_normalizados.iloc[:, 1:].corr()


import numpy as np
corr_filtered = corr.where((corr > 0.6) | (corr < -0.6))


fig = px.imshow(
    corr_filtered,
    labels=dict(x="Indicador", y="Indicador", color="Correlación"),
    title="Matriz de Correlación (>|0.6|) entre Indicadores",
    width=800,
    height=800,
    color_continuous_scale=px.colors.sequential.Turbo,
)
fig.show()

In [35]:
import plotly.express as px


indicador_x = df_normalizados.columns[3]  
indicador_y = df_normalizados.columns[4] 

fig = px.scatter(
    df_normalizados,
    x=indicador_x,
    y=indicador_y,
    hover_name=df_normalizados.columns[0],  
    color="Mean",  
    size="Mean",
    color_continuous_scale="Viridis",   
    title=f"Comparación entre {indicador_x} y {indicador_y} por País"
)
fig.show()